### PR TITLE
feat: added optimizations

### PR DESCRIPTION
**Pull request by tareq1988**
Added various WordPress optimization options

CleanShot 2024-05-25 at 19 28 44@2x

## Summary by CodeRabbit

- **New Features**
  - Introduced new utility classes for margin, width, padding, text alignment, and color.
  - Added an 'Optimizations' tab in the admin page for managing optimization settings.
  - Added customization options for the WordPress admin area, including removing the WordPress logo and various dashboard widgets.
  - Introduced methods to optimize WordPress by removing emojis, embed scripts, comments, and more.

- **Bug Fixes**
  - Updated the admin JavaScript to remove form update notices correctly.

- **Style**
  - Updated CSS classes for notification messages and form notices for better consistency and readability.

- **Chores**
  - Added action hooks for admin tab content rendering.

### CODE REVIEW

**Comment by tareq1988** [comment]
@saiftheboss7 can you assign this feature for testing?

**Comment by saiftheboss7** [comment]
@Rat01047 Bhai would look into it (assigned)

**Comment by tareq1988** [comment]
@Rat01047 we need to test if this feature is working properly.

**Comment by saiftheboss7** [comment]
From one user

> FlyWP has an option, DISABLE for XML & RSS feeds. However, the code is easily visible in the HTML of the site header. A general security practice is to remove the code from the HTML as well.

**Comment by Rat01047** [comment]
@tareq1988 bhai,
I had a few queries regarding optimization-feature - I have shared a detailed report in [Team-Testing](https://wedevs.slack.com/archives/C03RTF5PBGA/p1717666815980729).
Could you please review this?

CC: @saiftheboss7 bhai

**Pull request merged**
